### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by mitchchaiet** [andrewhoulbrook/china-reverseimage-transforms#1]
Hi Andrew,

I've been working to the best of my abilities to get these transforms up and running, on both Windows and macOS. I keep getting the following error on both OS from all three scripts:

Traceback (most recent call last):
  File "C:\Users\Mitch\Documents\MaltegoTransforms\china-reverseimage-transforms-master\baiduReverseImage.py", line 23, in <module>
    IMAGE_URL = m.getVar('url').decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'

Any ideas?

**Comment by andrewhoulbrook** [comment]
Hi Mitch,

Thanks for your message. You are certainly right. I have the same issue. 

I had thought this was old code that I clumsily modified and somehow butchered. Taking a closer look, this seems to be an error linked to using the built-in maltego.Image entity to call the transform (which i'm assuming is how you have tried to run the transforms too). 

According to the docs, maltego.Image should have a field named 'url', but using the Python transform library's 'getVar' keeps returning that error suggesting to it can't find the field. The XML for the maltego.Image entity also seems to indicate that there's a field named 'url'

      <Fields>
         <Field name="description" type="string" nullable="true" hidden="false" readonly="false" description="" displayName="Description">
            <SampleValue>Image</SampleValue>
         </Field>
         <Field name="url" type="url" nullable="true" hidden="false" readonly="false" description="" displayName="URL"/>
      </Fields>

I'm not sure what the issue is here. 

I created my own custom entity in Maltego (called it maltego.Webimage) with its own 'url' field and the transforms run fine. That's a quick work-around. 

The URL could also be passed in via the entity's main field and using sys.argv[0] in the script to read its value. No need for m.parseArguments(sys.argv) then.

**Comment by mitchaiet** [comment]
If I'm not mistaken, these scripts don't use [Maltego-TRX](https://github.com/paterva/maltego-trx) correct? I believe it's an update to the Python library these use.

**Comment by andrewhoulbrook** [comment]
Hi Mitch,

Thanks for your message. That's correct. These are legacy transforms and use the old [Python Local Library](https://docs.maltego.com/support/solutions/articles/15000019558-python-local-library-reference). That Probably explains some of the issues using the old getVar() method and the NoneType error. 

I'll have to find some time to update the scripts making use of the new Maltego-TRX. The scraping logic should be good (at the time of writing).
